title: Naja-Atra Docs
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://keijack.github.io/naja-atra-docs

aux_links:
  Folk: https://github.com/keijack/python-simple-http-server
